### ISSUE TITLE
get_workspaces fails for many workspaces

### ISSUE THREAD

**Issue by pixelrebel** [predat/pyIsis#2]
This may be unusual, but I have encountered an isis with 368 workspaces.  I'm not sure if this is related to large number of workspaces, but querying get_workspaces returns this error:

```
Traceback (most recent call last):
  File "pyisis-debug.py", line 7, in <module>
    workspaces = soapcon.get_workspaces()
  File "/Library/Python/2.7/site-packages/pyIsis-0.1.0-py2.7.egg/pyIsis/connection.py", line 187, in get_workspaces
    return self._client.service.GetWorkspaces(self._token['value'])['workspaces']['workspace']
  File "/Library/Python/2.7/site-packages/suds/client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 643, in send
    result = self.succeeded(binding, reply.message)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 678, in succeeded
    reply, result = binding.get_reply(self.method, reply)
  File "/Library/Python/2.7/site-packages/suds/bindings/binding.py", line 145, in get_reply
    replyroot = sax.parse(string=reply)
  File "/Library/Python/2.7/site-packages/suds/sax/parser.py", line 136, in parse
    sax.parse(source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 211, in feed
    self._err_handler.fatalError(exc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:93835: not well-formed (invalid token)
```

Looking at tcpflow the get_workpaces request is successfully returning all 368 workspaces, and the resulting xml is 26441 characters (roughly 450K in size).  

The same script works just fine on 6 different isises.

**Comment by pixelrebel** [comment]
If I use a less privileged user (one that has only read access to workspaces), I get a different error:
```
Traceback (most recent call last):
  File "pyisis-debug.py", line 7, in <module>
    workspaces = soapcon.get_workspaces()
  File "/Library/Python/2.7/site-packages/pyIsis-0.1.0-py2.7.egg/pyIsis/connection.py", line 187, in get_workspaces
    return self._client.service.GetWorkspaces(self._token['value'])['workspaces']['workspace']
TypeError: string indices must be integers
```
Again, this user type works just fine on all other isises on the network.

**Comment by predat** [comment]
Hello pixelrebel,

you could try to get workspaces directly with suds to see if you get a error:

``` python
from suds.client import Client
client = Client('http://isis-ip-address/?wsdl')
token = Client('agent123', 'Administrator', 'password') # admin login + password
client.service.GetWorkspaces(token)
```

if you get an error with those commands the problem come from suds; if not we need to investigate...

**Comment by pixelrebel** [comment]
I had the same error with suds.  In fact, I get a timeout when I simply call WEBConnection.get_server_info().  I'm not sure what's different here except for the large number of workspaces.  The Management Console Web GUI works just fine.  I'll close and reopen if I find out more information.
