### ISSUE TITLE
Parse Error with Nexis v2018.5

### ISSUE THREAD

**Issue by pixelrebel** [predat/pyIsis#7]
Thanks for the update in 0.2.3 which supports specifying a port for the latest version of Nexis.   I was also working on this, but was unable to parse the XML.  I also hit this snag in pyIsis 0.2.3.

```
Traceback (most recent call last):
  File "/opt/isis/myscript.py", line 300, in <module>
    webcon = pyIsis.Client(IP_ADDR, USERNAME, PASSWORD, port)
  File "/opt/isis/venv/lib/python2.7/site-packages/pyIsis/connection.py", line 58, in __init__
    self._client = osa.Client(url)
  File "/opt/isis/venv/lib/python2.7/site-packages/osa/client.py", line 107, in __init__
    parser = wsdl.WSDLParser(wsdl_url)
  File "/opt/isis/venv/lib/python2.7/site-packages/osa/wsdl.py", line 38, in __init__
    self.wsdl = xmlparser.parse_qualified_from_url(wsdl_url)
  File "/opt/isis/venv/lib/python2.7/site-packages/osa/xmlparser.py", line 105, in parse_qualified_from_url
    root = parse_qualified(page_handler, attr=attr)
  File "/opt/isis/venv/lib/python2.7/site-packages/osa/xmlparser.py", line 52, in parse_qualified
    for event, element in etree.iterparse(f, events):
  File "<string>", line 91, in next
cElementTree.ParseError: undefined entity: line 12, column 21
```

**Comment by pixelrebel** [comment]
Oops, I realized the second I posted this that I had the wrong port specified.  

Consider 0.2.3 verified to work with Nexis 2018.5! 

Thanks!!!
